### ISSUE TITLE
note: you need convert the original pretrained weights to d2 format by convert_to_d2.py

### ISSUE THREAD

**Issue by G-Apple1** [xiaohu2015/SwinT_detectron2#11]
Thanks for your nice project.

What do the note mean?

the weight i download from the “model” which in the table, that weight can't be used directly?

the downloaded weight also have to convert to d2 format?

I also want to know that the metric ”boxmap” is evaluated on the which datasets.

**Comment by xiaohu2015** [comment]
@G-Apple1 I mean that the original pretrained weight is for classification, but for detection, the classification is the backbone. In d2 model, the model parameters' keys (names) have been changed, so you need convert_to_d2.py to convert.

but if you use the weight I provided, you don't need to convert, because I have done the convertion.

COCO2017 datasets

**Comment by G-Apple1** [comment]
> @G-Apple1 I mean that the original pretrained weight is for classification, but for detection, the classification is the backbone. In d2 model, the model parameters' keys (names) have been changed, so you need convert_to_d2.py to convert.
> 
> but if you use the weight I provided, you don't need to convert, because I have done the convertion.
> 
> COCO2017 datasets

evaluated on coco2017val or coco2017test?

http://images.cocodataset.org/zips/val2017.zip 
http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip

http://images.cocodataset.org/zips/test2017.zip 
http://images.cocodataset.org/annotations/image_info_test2017.zip

**Comment by xiaohu2015** [comment]
@G-Apple1 val

**Comment by aarbelle** [comment]
@xiaohu2015 Where can I download the original imagenet pretrained weights?

**Comment by xiaohu2015** [comment]
@aarbelle you can donwload the weights from the offical git repo
