### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by Jerrrrykun** [xiaohu2015/SwinT_detectron2#17]
Hi, I am wondering how many GPUs you have used for reproducing the results. Is this model resource-intensive?

**Comment by xiaohu2015** [comment]
@L3str4nge Yes. Maybe you need a 8-V100 machine, because it need more GPU memory compared to ResNet50, I suggest that you can use amp to train.

**Comment by Jerrrrykun** [comment]
@xiaohu2015 Thx for your reply. I'm using 4 TitanXP for training the model. Could I know how many iterations you trained to reproduce the results on COCO 2017? I am using your pretrained Swint-T model for a cell instance segmentation task. But I find it quite hard to even surpass the R50 + maskRCNN model results(with 0.301 IoU). The Swint-T seems to need smaller lr compared with R50 model.

**Comment by xiaohu2015** [comment]
@Jerrrrykun You use the config file that I provided can reproduce the coco results. The optimizer used in training SwinT is adamw, so the lr is different with sdg.

**Comment by Jerrrrykun** [comment]
@xiaohu2015 I see, thanks.
