### ISSUE TITLE
version of torch

### ISSUE THREAD

**Issue by salehnia** [xiaohu2015/SwinT_detectron2#20]
Hi,
Thanks for sharing your Code. I tried to run convert_to_d2.py file to create model file. But i have an error and I guess it's because of torch version. Can you help me about step of running and please tell which version torch i should to use.

Thank you

**Comment by xiaohu2015** [comment]
maybe you can show some error message. For torch, I recommend 1.10+

**Comment by salehnia** [comment]
thanks for your answer.
I want to use of Swint in fsdet project as backbone. it use of torch 1.6.0.
my Error is:
data = pickle.load(f,encoding="latin1")
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

Thank you

**Comment by xiaohu2015** [comment]
it seems encoding iusse, you can utf-8 in your environment.

**Comment by salehnia** [comment]
it's defined encoding for detectron2, i tried it by encoding="bytes" too (with [this reference](https://docs.python.org/3/library/pickle.html#pickle.load))
Is your code compatible with torch version 1.6 ?
Can you share your .pkl file direct link for download?

Thanks

**Comment by xiaohu2015** [comment]
@salehnia hi, you should save weights as a `pth` file rather than `pkl`, https://github.com/xiaohu2015/SwinT_detectron2/blob/main/convert_to_d2.py#L16

**Comment by salehnia** [comment]
Hi, yes I did same work. Thanks...
but i have encoding error yet.

**Comment by xiaohu2015** [comment]
@salehnia it is very strange...

**Comment by salehnia** [comment]
Can you tell me please, you used of which version of detectron2 ?
I checked it with detectron2 = 0.6
torch =1.10.0
and now i have this Error:
allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

I guess I'm using of different version!

Thanks

**Comment by xiaohu2015** [comment]
yes, detectron2 = 0.6
torch =1.10.0

**Comment by salehnia** [comment]
@xiaohu2015 Thank you so much.
