### ISSUE TITLE
resnet related configuration in the yaml file

### ISSUE THREAD

**Issue by zhouzhouhhh** [xiaohu2015/SwinT_detectron2#24]
Hello, I would like to ask why there are parameters related to resnet in mask_rcnn_swint_T_FPN_3x.yaml. I think that the swin transformer replaces the original resnet as the backbone network, and there should be no resnet related configuration in the yaml file. Looking forward to your answer!
<img width="484" alt="image" src="https://user-images.githubusercontent.com/39587467/166640484-00136529-2b8f-45f5-8212-f379b15202ac.png">

**Comment by xiaohu2015** [comment]
It does't matter, in fact the yaml config in detectron2 includes all parameters of the model zoo, but here we use `build_swint_fpn_backbone` BACKBONE, so only the `SWINT` works.
