### ISSUE TITLE
faster_rcnn训练ap为nan

### ISSUE THREAD

**Issue by hejinsome** [xiaohu2015/SwinT_detectron2#25]
xiaohu，非常感谢你伟大的工作，
我用在上面训练faster-Rcnn，训练几万步，ap为nan，我也采用你faster_rcnn_swint_T.pth作为pre-tained； 我也一直用detectron2，还是比较熟悉这个开源框架。找不到原因，请明示！！

感谢！

**Comment by xiaohu2015** [comment]
用的是amp训练的吗？loss是一直下降的吗，突然出现nan吗？

**Comment by hejinsome** [comment]
非常感谢您的回复，真的很感谢。
问题一：由于我这个detectron2版本不支持amp，我没有在配置里面删除了，这个影响很大吗？
问题二： ap nan我看训练过程中的val 都是nan；
问题三：训练过程中loss开始都比较小，很奇怪。后面下降很少；
问题四：学习率config文件开始设置的0.0001，这个需要这样配置吗？

我将学习率修改为0.02，还是系统默认，5000步验证ap为23.6。

**Comment by xiaohu2015** [comment]
用了amp可能容易出现nan，看来不是这个问题。你有其他模型的baseline结果吗？

**Comment by hejinsome** [comment]
还在训练，不过很奇怪，我现在10W步，AP验证只有26.1，同时loss一直在0.6-0.7徘徊。 我的初始学习率是0.02.  STEPS: (210000, 250000)。感觉是有问题的。

**Comment by hejinsome** [comment]
还在训练，不过很奇怪，我现在10W步，AP验证只有26.1，同时loss一直在0.6-0.7徘徊。 我的初始学习率是0.02.  STEPS: (210000, 250000)。感觉是有问题的。

> 用了amp可能容易出现nan，看来不是这个问题。你有其他模型的baseline结果吗？

**Comment by hejinsome** [comment]
> 用了amp可能容易出现nan，看来不是这个问题。你有其他模型的baseline结果吗？

我的qq：45597399，方便相互加一下？好进一步交流。

**Comment by xiaohu2015** [comment]
@hejinsome 你加群吧772899652
