### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Mastemace** [xiaohu2015/SwinT_detectron2#3]
Hi, thank you for your nice work. I can confirm it works and yield nice results even if it is trained on a custom dataset.

Can you please add a license to the repository? E.g., MIT. It is necessary to use the source code correctly and not 'steal' it. Thank you:)

**Comment by xiaohu2015** [comment]
@Mastemace I added a MIT license.

**Comment by Mastemace** [comment]
Thank you, I appreciate it.
