### ISSUE TITLE
Faster R-CNN Pre-trained Model

### ISSUE THREAD

**Issue by Alchemistyui** [xiaohu2015/SwinT_detectron2#5]
Hi, thank you very much for your graceful work. 
I would like to ask if you have any plans to release the Faster R-CNN pre-trained model? I would appreciate it if you could do this, it would help me a lot.
Thank you very much!

**Comment by xiaohu2015** [comment]
@Alchemistyui you can get faster rcnn model here: https://github.com/xiaohu2015/SwinT_detectron2/releases/download/v1.1/faster_rcnn_swint_T.pth

**Comment by Alchemistyui** [comment]
Thank you very much!

**Comment by Alchemistyui** [comment]
@xiaohu2015 Sorry to bother you again, but would you mind uploading the pre-trained RetinaNet model? I want to compare the performance.
Thanks again.

**Comment by xiaohu2015** [comment]
@Alchemistyui Ok, you can download now

**Comment by Alchemistyui** [comment]
Thank you very much!!
