### ISSUE TITLE
Detectron2 version

### ISSUE THREAD

**Issue by tandes** [xiaohu2015/SwinT_detectron2#6]
Hi, thank you for your nice work.
Can you tell me which detectron2 version have been used? 
I have a problem when evaluate the model(training by myself or downloading from the [link](https://github.com/xiaohu2015/SwinT_detectron2/releases/download/v1.1/faster_rcnn_swint_T.pth))

> [05/06 11:12:29] d2.evaluation.coco_evaluation WARNING: No predictions from the model!
> [05/06 11:12:29] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
> [05/06 11:12:29] d2.evaluation.testing INFO: copypaste: Task: bbox
> [05/06 11:12:29] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [05/06 11:12:29] d2.evaluation.testing INFO: copypaste: nan,nan,nan,nan,nan,nan

I want to make sure whether it is a version issue, thanks~

**Comment by xiaohu2015** [comment]
@tandes Sorry, you can use https://github.com/xiaohu2015/SwinT_detectron2/blob/main/configs/SwinT/faster_rcnn_swint_T_FPN_3x_.yaml to test.

> I use the dafault config PIXEL_MEAN, PIXEL_STD, INPUT.FORMAT , that is a mistake, but it affects performance negligently.

you can see this issue https://github.com/xiaohu2015/SwinT_detectron2/issues/1

**Comment by tandes** [comment]
> @tandes Sorry, you can use https://github.com/xiaohu2015/SwinT_detectron2/blob/main/configs/SwinT/faster_rcnn_swint_T_FPN_3x_.yaml to test.
> 
> > I use the dafault config PIXEL_MEAN, PIXEL_STD, INPUT.FORMAT , that is a mistake, but it affects performance negligently.
> 
> you can see this issue #1

Thanks, it worked.
