### ISSUE TITLE
I have a error. KeyError: 'Non-existent config key: MODEL.SWINT'

### ISSUE THREAD

**Issue by leesangjoon1** [xiaohu2015/SwinT_detectron2#8]
I run training using detectron2

but this error comes up - KeyError: 'Non-existent config key: MODEL.SWINT'
How do I do??? 

Thank you!

**Comment by xiaohu2015** [comment]
@leesangjoon1 you should check if you add_swint_config in you train script.

**Comment by leesangjoon1** [comment]
> @leesangjoon1 you should check if you add_swint_config in you train script.

Please Could you teach me how to add the swint config??? I can't find how to add it

**Comment by xiaohu2015** [comment]
@leesangjoon1 ref train_net.py

**Comment by leesangjoon1** [comment]
> @leesangjoon1 ref train_net.py

ref?? what it means??

**Comment by xiaohu2015** [comment]
@leesangjoon1 train_net.py line 40 and 167: from swint import add_swint_config
