### ISSUE TITLE
I want to check if the model is trained well so I do inference but in cfg.merge_from_file, MODEL.SWINT Non-existent error comes up again

### ISSUE THREAD

**Issue by leesangjoon1** [xiaohu2015/SwinT_detectron2#9]
from detectron2.utils.visualizer import ColorMode
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import json
import pandas as pd
from random import randint
import torch, torchvision

import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import cv2
import random
import matplotlib.pyplot as plt

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog

from swint import add_swint_config

from detectron2.data.datasets import register_coco_instances
register_coco_instances("data_train", {}, "/home/sangjoon/detectron2/sangjoon/for_newthing_0331/white_train.json", "/home/sangjoon/detectron2/sangjoon/white_train2020")
register_coco_instances("data_val", {}, "/home/sangjoon/detectron2/sangjoon/for_newthing_0331/white_test.json", "/home/sangjoon/detectron2/sangjoon/white_test2020")

import os
import numpy as np
import json
from detectron2.structures import BoxMode
import itertools

from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()

cfg.merge_from_file("/home/sangjoon/detectron2/configs/COCO-Detection/faster_rcnn_swint_T_FPN_3x_.yaml") cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = "/home/sangjoon/SwinT_detection2/real_white_weights/model_0015499.pth"  # initialize from model zoo

trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)

cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
predictor = DefaultPredictor(cfg)

-----------------------------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-9b47a27d2009> in <module>
      1 cfg = get_cfg()
      2 from swint import add_swint_config
----> 3 cfg.merge_from_file("/home/sangjoon/detectron2/configs/COCO-Detection/faster_rcnn_swint_T_FPN_3x_.yaml")
      4 # cfg.DATALOADER.NUM_WORKERS = 4
      5 cfg.MODEL.WEIGHTS = "/home/sangjoon/SwinT_detection2/real_white_weights/model_0015499.pth"  # initialize from model zoo

~/detectron2/detectron2/config/config.py in merge_from_file(self, cfg_filename, allow_unsafe)
     52 
     53         if loaded_ver == self.VERSION:
---> 54             self.merge_from_other_cfg(loaded_cfg)
     55         else:
     56             # compat.py needs to import CfgNode

~/.conda/envs/mmdetection/lib/python3.7/site-packages/fvcore/common/config.py in merge_from_other_cfg(self, cfg_other)
    121             BASE_KEY not in cfg_other
    122         ), "The reserved key '{}' can only be used in files!".format(BASE_KEY)
--> 123         return super().merge_from_other_cfg(cfg_other)
    124 
    125     def merge_from_list(self, cfg_list: List[str]) -> Callable[[], None]:

~/.conda/envs/mmdetection/lib/python3.7/site-packages/yacs/config.py in merge_from_other_cfg(self, cfg_other)
    215     def merge_from_other_cfg(self, cfg_other):
    216         """Merge `cfg_other` into this CfgNode."""
--> 217         _merge_a_into_b(cfg_other, self, self, [])
    218 
    219     def merge_from_list(self, cfg_list):

~/.conda/envs/mmdetection/lib/python3.7/site-packages/yacs/config.py in _merge_a_into_b(a, b, root, key_list)
    476             if isinstance(v, CfgNode):
    477                 try:
--> 478                     _merge_a_into_b(v, b[k], root, key_list + [k])
    479                 except BaseException:
    480                     raise

~/.conda/envs/mmdetection/lib/python3.7/site-packages/yacs/config.py in _merge_a_into_b(a, b, root, key_list)
    489                 root.raise_key_rename_error(full_key)
    490             else:
--> 491                 raise KeyError("Non-existent config key: {}".format(full_key))
    492 
    493 

KeyError: 'Non-existent config key: MODEL.SWINT'

How do I fix it??

**Comment by xiaohu2015** [comment]
@leesangjoon1 you need add swint config in cfg:

```python
    cfg = get_cfg()
    add_swint_config(cfg)
````
